Datasets:
  cdr:
    enabled: true
    cleaning notebooks:
      - clean_cdr.ipynb
    compression notebooks:
      - create_datasets_for_website.ipynb
    sheet key: 15othpOTOwB25_ccde4jHK3MaQDAvQyJSXJIVL3eihHg
  ois:
    enabled: true
    cleaning notebooks:
      - clean_ois_civilians_shot.ipynb
      - clean_ois_Dofficers_shot.ipynb
    compression notebooks:
      - create_datasets_for_website.ipynb
    sheet key: 1mrdGvABFCUYo68TPGWaT22l1e1qkdgVYBal9cs6sdwc

Email Settings:
  sender:
    - aiden.yang@texasjusticeinitiative.org
  recipients:
    - aidenyang@texasjusticeinitiative.org
    - eva.ruth@texasjusticeinitiative.org
  region: us-east-1
