Datasets:
  cdr:
    name: cdr
    cleaning_notebooks:
      - clean_cdr.ipynb
    compression_notebooks:
      - create_datasets_for_website.ipynb
    sheet_key: 15othpOTOwB25_ccde4jHK3MaQDAvQyJSXJIVL3eihHg
  ois:
    name: ois
    cleaning_notebooks:
      - clean_ois_civilians_shot.ipynb
      - clean_ois_officers_shot.ipynb
    compression_notebooks:
      - create_datasets_for_website.ipynb
    sheet_key: 1mrdGvABFCUYo68TPGWaT22l1e1qkdgVYBal9cs6sdwc

Emailer:
  sender:
    - aiden.yang@texasjusticeinitiative.org
  recipients:
    - aidenyang@texasjusticeinitiative.org
    - eva.ruth@texasjusticeinitiative.org
  region: us-east-1
